// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0oMjRgKbVTLfEqe0wiS2lH4f0saLy67w',
    appId: '1:1037858245018:android:6586a58bfd5b012ae3d223',
    messagingSenderId: '1037858245018',
    projectId: 'ventures-ai-app-e3650',
    storageBucket: 'ventures-ai-app-e3650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdEyLVPuEpFQjlpvTgipyFqDptj3WeqCw',
    appId: '1:1037858245018:ios:7eb5346462b18072e3d223',
    messagingSenderId: '1037858245018',
    projectId: 'ventures-ai-app-e3650',
    storageBucket: 'ventures-ai-app-e3650.firebasestorage.app',
    androidClientId: '1037858245018-vjp2dkg3pud5589vf6bufuaq16o7v6fq.apps.googleusercontent.com',
    iosClientId: '1037858245018-njj8rebp6afdb36b10rqfp3cvecrnbeq.apps.googleusercontent.com',
    iosBundleId: 'com.example.venture',
  );

}